module.exports = {
  type: "object",
  properties: {
    _id: {
      type: "string",
      description: "Autogenerated Id of the staff",
      readOnly: true,
    },
    firstName: {
      type: "string",
      description: "The first name of the staff",
      example: "Solomon",
    },
    lastName: {
      type: "string",
      description: "The last name of the staff",
      example: "Grundy",
    },
    email: {
      type: "string",
      description: "Email address of the staff",
      example: "solomongrundy@school.edu",
    },
    phone: {
      type: "string",
      description: "The phone number of the staff",
      example: "09012345678",
    },
    subjects: {
      type: "array",
      description: "subject the staff takes",
      example: ["Maths", "Physics"],
    },
    classIds: {
      type: "array",
      description: "Autogenerated ID of the classes",
      readOnly: true,
    },
    hireDate: {
      type: "string",
      format: "date-time",
      description: "The date",
    },
    address: {
      type: "object",
      description: "Optional user address",
      properties: {
        street: { type: "string", example: "123 Applebay Street" },
        city: { type: "string", example: "Gotham" },
        state: { type: "string", example: "New York" },
        zip: { type: "string", example: "10001" },
        country: { type: "string", example: "USA" },
      },
    },
    qualification: {
      type: "string",
      description: "Qualification of the staff",
      example: "Physics",
    },
    status: {
      type: "string",
      description: "This is to know if the staff is still hired",
      example: "active",
    },
    createdAt: {
      type: "string",
      format: "date-time",
      readOnly: true,
      description: "Timestamp when the staff account was created",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
      readOnly: true,
      description: "Timestamp when the staff account was last updated",
    },
  },
  required: [
    "firstName",
    "lastName",
    "email",
    "classIds",
    "hireDate",
    "address",
    "qualification",
    "status",
  ],
};
