module.exports = {
  type: "object",
  properties: {
    _id: {
      type: "string",
      description: "Autogenerated ID of the class",
      readOnly: true,
    },
    title: {
        type: "string",
        description: "The title for the class",
        example: "Intro to calculus",
    },
    code: {
        type: "string",
        description: "A code that signifies a class",
        example: "MTH104",
    },
    room: {
        type: "string",
        description: "The physical location of the class within the campus",
        example: "Block A - Room 10",
    },
    schedule: {
        type: "string",
        description: "The time at wich the class takes place",
        example: "MWF 10:00 - 11:00",
    }
  },
  required: [
    "title",
    "code",
    "room",
    "schedule",
  ],
};
