module.exports = {
  type: "object",
  properties: {
    _id: {
      type: "string",
      description: "Autogenerated ID of the class",
      readOnly: true,
    },
    name: {
        type: "string",
        description: "The name of the degree",
        example: "Bachelor of Computer Science",
    },
    durationYears: {
        type: "number",
        description: "the number of years needed for the degree",
        example: 4,
    },
    department: {
        type: "string",
        description: "The department for the degree",
        example: "Computer Science",
    },
    accreditation: {
        type: "string",
        description: "the accreditation earned by comepleteing the degree",
        example: "NCC",
    }
  },
  required: [
    "title",
    "code",
    "room",
    "schedule",
  ],
};
